package oracle.summit.model.views;

import oracle.summit.base.SummitViewObjectImpl;
import oracle.summit.model.views.common.InventoryVO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 06 15:25:32 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InventoryVOImpl extends SummitViewObjectImpl implements InventoryVO {
    /**
     * This is the default constructor (do not remove).
     */
    public InventoryVOImpl() {
    }


    public void populateInventoryForProduct( String productId ) {
          applyViewCriteria(getViewCriteria("InventoryVOCriteria"));
          setinputProductId( productId );
          executeQuery();
    }

    /**
     * Returns the variable value for Variable.
     * @return variable value for Variable
     */
    public String getinputProductId() {
        return (String)ensureVariableManager().getVariableValue("inputProductId");
    }

    /**
     * Sets <code>value</code> for variable Variable.
     * @param value value to bind as Variable
     */
    public void setinputProductId(String value) {
        ensureVariableManager().setVariableValue("inputProductId", value);
    }
}
