package oracle.summit.model.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 07 14:52:54 IST 2012
// ---------------------------------------------------------------------
public interface InventoryVO extends ViewObject {
    void populateInventoryForProduct(String productId);
}
