package oracle.summit.model.views.client;

import oracle.jbo.client.remote.ViewUsageImpl;

import oracle.summit.model.views.common.InventoryVO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 07 14:52:54 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InventoryVOClient extends ViewUsageImpl implements InventoryVO {
    /**
     * This is the default constructor (do not remove).
     */
    public InventoryVOClient() {
    }

    public void populateInventoryForProduct(String productId) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"populateInventoryForProduct",new String [] {"java.lang.String"},new Object[] {productId});
        return;
    }
}
